#!/bin/sh

DIRECTORY="./node_modules"
if [ ! -d "$DIRECTORY" ]; then
  echo "WARNING: Cannot find node_modules folder, please run 'npm install' first"
fi

if [ -d "$DIRECTORY" ]; then
  ./node_modules/.bin/post-checkout "$@"
fi
