#!/bin/sh

DIRECTORY="./node_modules"
if [ ! -d "$DIRECTORY" ]; then
  echo "Cannot find node_modules folder, please run 'npm install' first"
  exit -1
fi

if [ ! -x "$(command -v node)" ]; then
  echo "Node binary not found, please ensure it's properly setup"
  exit -1
fi

./node_modules/.bin/post-commit "$@"
