#!/bin/sh

DIRECTORY="./node_modules"
if [ ! -d "$DIRECTORY" ]; then
  echo "WARNING: Cannot find node_modules folder, please run 'npm install' first"
fi

if [ ! -x "$(command -v node)" ]; then
  echo "WARNING: Node binary not found, please ensure it's properly setup"
fi

if [ -d "$DIRECTORY" ] && [ -x "$(command -v node)" ]; then
  ./node_modules/.bin/post-checkout "$@"
fi
